/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#d3e4fe',
        'on-primary-container':      '#8590a6',
        'on-tertiary':               '#ffffff',
        'primary-fixed-dim':         '#bcc7de',
        'inverse-surface':           '#213145',
        'surface-container':         '#e5eeff',
        'secondary':                 '#006591',
        'on-secondary-container':    '#004666',
        'surface':                   '#f8f9ff',
        'on-tertiary-container':     '#a38c6a',
        'primary-fixed':             '#d8e3fb',
        'on-tertiary-fixed':         '#271902',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'inverse-on-surface':        '#eaf1ff',
        'secondary-container':       '#39b8fd',
        'on-secondary-fixed-variant':'#004c6e',
        'inverse-primary':           '#bcc7de',
        'background':                '#f8f9ff',
        'on-secondary-fixed':        '#001e2f',
        'surface-container-low':     '#eff4ff',
        'on-background':             '#0b1c30',
        'surface-bright':            '#f8f9ff',
        'on-secondary':              '#ffffff',
        'surface-variant':           '#d3e4fe',
        'secondary-fixed':           '#c9e6ff',
        'tertiary':                  '#1e1200',
        'on-error-container':        '#93000a',
        'on-surface-variant':        '#45474c',
        'surface-tint':              '#545f73',
        'secondary-fixed-dim':       '#89ceff',
        'surface-container-high':    '#dce9ff',
        'on-surface':                '#0b1c30',
        'primary':                   '#091426',
        'on-primary-fixed':          '#111c2d',
        'tertiary-fixed-dim':        '#ddc39d',
        'tertiary-fixed':            '#fadfb8',
        'on-primary-fixed-variant':  '#3c475a',
        'surface-container-lowest':  '#ffffff',
        'outline':                   '#75777d',
        'primary-container':         '#1e293b',
        'on-primary':                '#ffffff',
        'error':                     '#ba1a1a',
        'outline-variant':           '#c5c6cd',
        'tertiary-container':        '#35260c',
        'on-tertiary-fixed-variant': '#564427',
        'surface-dim':               '#cbdbf5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        base:            '4px',
        gutter:          '24px',
        sm:              '8px',
        xs:              '4px',
        md:              '16px',
        'margin-desktop':'40px',
        'margin-mobile': '16px',
        xl:              '32px',
        lg:              '24px',
      },
      fontFamily: {
        'headline-md':       ['IBM Plex Sans', 'sans-serif'],
        'label-md':          ['IBM Plex Sans', 'sans-serif'],
        'body-md':           ['IBM Plex Sans', 'sans-serif'],
        'body-lg':           ['IBM Plex Sans', 'sans-serif'],
        'headline-lg-mobile':['IBM Plex Sans', 'sans-serif'],
        'display-lg':        ['IBM Plex Sans', 'sans-serif'],
        'headline-lg':       ['IBM Plex Sans', 'sans-serif'],
        'body-sm':           ['IBM Plex Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-md':       ['24px', { lineHeight:'32px', fontWeight:'600' }],
        'label-md':          ['12px', { lineHeight:'16px', letterSpacing:'0.05em', fontWeight:'600' }],
        'body-md':           ['16px', { lineHeight:'24px', fontWeight:'400' }],
        'body-lg':           ['18px', { lineHeight:'28px', fontWeight:'400' }],
        'headline-lg-mobile':['28px', { lineHeight:'36px', fontWeight:'600' }],
        'display-lg':        ['48px', { lineHeight:'56px', letterSpacing:'-0.02em', fontWeight:'700' }],
        'headline-lg':       ['32px', { lineHeight:'40px', letterSpacing:'-0.01em', fontWeight:'600' }],
        'body-sm':           ['14px', { lineHeight:'20px', fontWeight:'400' }],
      },
    },
  },
  plugins: [],
}